Desktop version
elhamatokhi/portfolio-micro pull request #4
Opened 2022-06-07 21:05 UTC by elhamatokhi

- In this pull request I created a new branch.
- I added media queries to make my website responsive.

2022-06-07 22:25 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Elhama, 
 ### You have been doing a tremendous job so far :ok_hand:

## To Highlight 🎉
GitHub flow is followed. :heavy_check_mark:
README is professional. :heavy_check_mark:
## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
**_Note: Please do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-06-07 22:25 UTC, SajjadAhmad14 commented on index.html
>      <div class="mainContainer">
The decoration images for the headline are not positioned correctly. Kindly see the design and place them in the right position.

Your design:
![yours-head](https://user-images.githubusercontent.com/35504149/172493042-18d9e1f0-fee7-4653-880f-a03c835e7835.png)

Original design:

![head-o](https://user-images.githubusercontent.com/35504149/172493076-bd48f4f3-449e-486d-9ca6-77c753e1c5aa.png)

2022-06-07 22:25 UTC, SajjadAhmad14 commented on index.html
> -        <div class="card card1">
The work section has broken images for all the projects on both mobile and desktop views. The title should have `#091E42` color. Moreover please use the hover effect for the `See Project` button.
![picture](https://user-images.githubusercontent.com/35504149/172493176-71626a13-e6be-4495-ac64-d93cd7bd5d47.png)

2022-06-07 22:25 UTC, SajjadAhmad14 commented on style.css
> +  #AboutmySelf {
The color for the `About` section title should be `#091E42` and the color for the `Get My Resume` button text should be `#396DF2`. The `Get My Resume` button should have a hover effect as defined in the design. Moreover, `Languages` should have icons as can be seen in the design.


Your design:
![your-languages](https://user-images.githubusercontent.com/35504149/172493313-7861581f-60a1-4fa3-9187-2ddf1595aca7.png)


Original design:
![languages](https://user-images.githubusercontent.com/35504149/172493339-1ffd36af-31eb-4661-9095-37f486bbd668.png)

2022-06-09 13:36 UTC, elhamatokhi commented on style.css
> +  #AboutmySelf {
Thanks for your kind review.
I have added some functionality, I think we just need to click on it.

2022-06-09 13:46 UTC, algerina approved these changes
Hi @elhamatokhi ,
 
Good job so far!

May I highlight the following:

- The repo looks professional. :heavy_check_mark: 
- There are no linter errors :heavy_check_mark: 
- You have descriptive PR :heavy_check_mark: 
- Your project looks awesome :heavy_check_mark: 
- You have implemented all the changes required by the previews TSE :heavy_check_mark: 

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
  

<img src="https://media0.giphy.com/media/fpzYhFGJZ9xPW/giphy.gif"/>
 
 ## Optional suggestions
 
 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-06-10 13:48 UTC, merged